# Generated by Django 5.1.7 on 2025-04-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='falta',
            field=models.BooleanField(default=False),
        ),
    ]
