# Generated by Django 5.1.7 on 2025-04-03 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0002_asistencia_falta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificacion',
            name='fecha',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='matricula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='falta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='presente',
            field=models.BooleanField(default=False),
        ),
    ]
