# Generated by Django 5.1.7 on 2025-04-03 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_escolar', '0003_remove_calificacion_fecha_alter_alumno_apellido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='falta',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='presente',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='estado',
            field=models.CharField(choices=[('P', 'Presente'), ('F', 'Falta'), ('R', 'Retardo')], default='P', max_length=1),
        ),
    ]
